  spring:
    application:
      name: config-dev
  eureka:
    instance:
      prefer-ip-address: true
      ip-address: 127.0.0.1
      hostname: localhost
      instance-id: ${spring.application.name}:${server.port}
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
